# Generated by Django 6.0 on 2025-12-15 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_messages', models.BooleanField(default=True)),
                ('push_comments', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('email_news', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='users.user')),
            ],
        ),
    ]
