# Generated by Django 6.0 on 2025-12-15 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usernotificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('primary_color', models.CharField(default='#4b7bec', max_length=7)),
                ('font_family', models.CharField(choices=[('system', 'System default'), ('sans', 'Sans Serif'), ('serif', 'Serif'), ('mono', 'Monospace')], default='system', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to='users.user')),
            ],
        ),
    ]
