# Generated by Django 6.0 on 2025-12-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userthemesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userthemesettings',
            name='theme_mode',
        ),
        migrations.AddField(
            model_name='userthemesettings',
            name='skin',
            field=models.CharField(choices=[('webix', 'Webix'), ('material', 'Material'), ('mini', 'Mini'), ('flat', 'Flat'), ('compact', 'Compact'), ('contrast', 'Contrast'), ('willow', 'Willow')], default='webix', max_length=20),
        ),
    ]
