# Generated by Django 6.0 on 2025-12-16 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userthemesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userthemesettings',
            name='theme_mode',
        ),
        migrations.AddField(
            model_name='userthemesettings',
            name='skin',
            field=models.CharField(choices=[('material', 'Material'), ('mini', 'Mini'), ('flat', 'Flat'), ('compact', 'Compact'), ('contrast', 'Contrast'), ('willow', 'Willow')], default='material', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(default='public', help_text='Profile visibility setting, e.g. public/friends/private', max_length=20)),
                ('show_email', models.BooleanField(default=False, help_text="Whether the user's email is visible to others")),
                ('data_sharing', models.BooleanField(default=False, help_text='Whether anonymized data can be shared')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='users.user')),
            ],
        ),
    ]
