# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userthemesettings_theme_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivacysettings',
            name='profile_visibility',
            field=models.CharField(
                choices=[
                    ('public', 'Public'),
                    ('friends', 'Friends only'),
                    ('private', 'Only me'),
                ],
                default='public',
                max_length=20
            ),
        ),
    ]

