# Generated by Django 6.0 on 2025-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userthemesettings_theme_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthemesettings',
            name='skin',
            field=models.CharField(choices=[('material', 'Material'), ('mini', 'Mini'), ('flat', 'Flat'), ('compact', 'Compact'), ('contrast', 'Contrast'), ('willow', 'Willow')], default='material', max_length=20),
        ),
    ]
