# Generated by Django 6.0 on 2025-12-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userthemesettings_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthemesettings',
            name='font_family',
            field=models.CharField(choices=[('default', 'Default'), ('system', 'System default'), ('sans', 'Sans Serif'), ('serif', 'Serif'), ('mono', 'Monospace')], default='default', max_length=20),
        ),
    ]
