# Generated by Django 6.0 on 2025-12-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userthemesettings_font_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthemesettings',
            name='font_family',
            field=models.CharField(choices=[('system', 'System default'), ('sans', 'Sans Serif'), ('serif', 'Serif'), ('mono', 'Monospace')], default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Only me')], default='public', max_length=20)),
                ('show_email', models.BooleanField(default=False)),
                ('data_sharing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='users.user')),
            ],
        ),
    ]
